//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestCom.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to build an application configuration: {0}..
        /// </summary>
        internal static string ConfigBuildError0 {
            get {
                return ResourceManager.GetString("ConfigBuildError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; not found in the configuration file..
        /// </summary>
        internal static string ConfigMissingKey0 {
            get {
                return ResourceManager.GetString("ConfigMissingKey0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the configuration file {0}: {1}..
        /// </summary>
        internal static string ConfigReadError01 {
            get {
                return ResourceManager.GetString("ConfigReadError01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending data to the NATS server..
        /// </summary>
        internal static string DataSendingError {
            get {
                return ResourceManager.GetString("DataSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to receive data..
        /// </summary>
        internal static string PortDataReceiveError {
            get {
                return ResourceManager.GetString("PortDataReceiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial port with the given name &apos;{0}&apos; not found..
        /// </summary>
        internal static string PortNotFoundError0 {
            get {
                return ResourceManager.GetString("PortNotFoundError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening port &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string PortOpenError01 {
            get {
                return ResourceManager.GetString("PortOpenError01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started listening the COM port..
        /// </summary>
        internal static string StartWorking {
            get {
                return ResourceManager.GetString("StartWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped listening the COM port..
        /// </summary>
        internal static string StopWorking {
            get {
                return ResourceManager.GetString("StopWorking", resourceCulture);
            }
        }
    }
}
